### ISSUE TITLE
-subs-only is broken

### ISSUE THREAD

**Issue by leesoh** [tomnomnom/assetfinder#13]
Unless I'm reading this incorrectly https://github.com/tomnomnom/assetfinder/blob/master/main.go#L90 will continue execution as normal if the identified domain doesn't match the root. I haven't tested but wouldn't a `return` be a better fit here?

I'll take a poke at this if I get some time, just adding it here for tracking purposes.

**Comment by leesoh** [comment]
Weird. Was getting a bunch of unrelated stuff last night, now can't replicate. Closing.

**Comment by leesoh** [comment]
I am not crazy. Steps to reproduce

`echo target.com | assetfinder -subs-only | anew blah`

If you leave off the final pipe, it works as expected, otherwise it ignores subs-only.

**Comment by tomnomnom** [comment]
Hey!

Unfortunately the fix for this needs to be a little different. Under your proposed change the output would stop as soon as *any* result that isn't a subdomain is found - even if there are more domains to process. 

I think the proper fix here is to move the `subsOnly` check into the loop that writes to the output channel :)

I'll do that now, sorry!
